[functions]
  external_node_modules = ["express", "axios", "emoji-name-map", "github-username-regex", "upgrade", "word-wrap"]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  force = true
  status = 200

[[redirects]]
  from = "/"
  to = "https://github.com/anuraghazra/github-readme-stats"
  status = 301
  force = true

